packages:
  - apps/*
  - components/*
  - configs/*
catalog:
  "@svebcomponents/build": 0.0.4
  "@svebcomponents/ssr": 0.0.5
  "@svebcomponents/auto-options": 0.0.4
  "@sveltejs/adapter-auto": 6.0.0
  "@sveltejs/kit": 2.20.5
  "@sveltejs/package": 2.3.10
  "@sveltejs/vite-plugin-svelte": 5.0.3
  "@tsconfig/strictest": 2.0.5
  "@tsconfig/svelte": 5.0.4
  "@types/node": 22.14.1
  eslint: 9.24.0
  "@eslint/js": 9.24.0
  eslint-config-prettier: 10.1.2
  eslint-plugin-svelte: 3.5.1
  globals: 16.0.0
  prettier: 3.5.3
  prettier-plugin-svelte: 3.3.3
  rollup: 4.40.0
  svelte: 5.28.2
  svelte-check: 4.1.6
  turbo: 2.5.2
  typescript: 5.8.3
  typescript-eslint: 8.29.1
  vite: 6.2.6
  vitest: 3.1.1
