packages:
  - apps/*
  - components/*
  - configs/*
catalog:
  "@svebcomponents/build": 0.0.7
  "@svebcomponents/ssr": 0.0.7
  "@sveltejs/adapter-auto": 6.0.0
  "@sveltejs/kit": 2.20.5
  "@sveltejs/vite-plugin-svelte": 5.0.3
  "@tsconfig/strictest": 2.0.5
  "@tsconfig/svelte": 5.0.4
  eslint: 9.24.0
  "@eslint/js": 9.24.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-svelte: 3.5.1
  globals: 16.0.0
  prettier: 3.5.3
  prettier-plugin-svelte: 3.3.3
  svelte: 5.34.7
  svelte-check: 4.1.6
  turbo: 2.5.2
  typescript: 5.8.3
  typescript-eslint: 8.29.1
  vite: 6.2.6
