name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: install deps
        run: pnpm install

      - name: type check
        run: pnpm check

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build
