name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: install deps
        run: pnpm install

      - name: install browser
        run: pnpm --filter svelte-kit exec playwright install --with-deps chromium

      - name: type check
        run: pnpm check

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
